# Generated by Django 2.0 on 2021-05-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='客户端名称')),
                ('fraction', models.IntegerField(verbose_name='分数')),
            ],
            options={
                'verbose_name': '排行榜',
                'verbose_name_plural': '排行榜',
            },
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together={('fraction',)},
        ),
    ]
