# Generated by Django 2.0 on 2021-05-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
