# Generated by Django 2.0 on 2021-05-25 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='fraction',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(1)], verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='客户端名称'),
        ),
    ]
