# Generated by Django 2.0 on 2021-05-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210528_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(max_length=200, verbose_name='客户端名称'),
        ),
    ]
